### ISSUE TITLE
第九章源码编译崩溃

### ISSUE THREAD

**Issue by hbbdzry** [hejunlin2013/AVBookCode#10]
第九章源码编译崩溃，
06-24 11:14:34.229 22609-22659/com.hejunlin.ffmpegpushcamerastream E/HAL: load: id=gralloc != hmi->id=gralloc
06-24 11:14:34.229 22609-22659/com.hejunlin.ffmpegpushcamerastream I/OpenGLRenderer: Initialized EGL, version 1.4
06-24 11:14:34.312 22609-22609/com.hejunlin.ffmpegpushcamerastream E/Camera: Camera new cameraInitNormal:0
06-24 11:14:34.416 22609-22620/com.hejunlin.ffmpegpushcamerastream E/Camera: notify error: 2, and: 0
06-24 11:14:34.968 22609-22609/com.hejunlin.ffmpegpushcamerastream E/Camera: Camera new cameraInitNormal:0
06-24 11:14:35.005 22609-22609/com.hejunlin.ffmpegpushcamerastream E/Camera: Error 2
06-24 11:14:35.007 22609-22609/com.hejunlin.ffmpegpushcamerastream I/Choreographer: Skipped 38 frames!  The application may be doing too much work on its main thread.
06-24 11:15:04.932 22609-22787/com.hejunlin.ffmpegpushcamerastream I/AudioRecordPermission: remindWithResult:false
06-24 11:15:04.932 22609-22787/com.hejunlin.ffmpegpushcamerastream I/HwAudioRecordImpl: HwAudioRecordImpl
06-24 11:15:04.932 22609-22787/com.hejunlin.ffmpegpushcamerastream I/HwAudioRecordImpl: checkRecordActive
06-24 11:15:04.936 22609-22787/com.hejunlin.ffmpegpushcamerastream I/HwAudioRecordImpl: sendStateChangedIntent, state=3

请问如何解决

**Comment by smartyuge** [comment]
没有完整日志信息，可以贴下完整日志信息
