### ISSUE TITLE
ffmpeg在windows用MSYS2书中脚本不能执行

### ISSUE THREAD

**Issue by kaiwmtnk** [hejunlin2013/AVBookCode#12]
# 脚本如下
#!/bin/bash
make clean
export NDK=C:/Users/Administrator/AppData/Local/Android/Sdk/ndk-bundle
export SYSROOT=$NDK/platforms/android-28/arch-arm
export TOOLCHAIN=$NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64
export CPU=arm
export PREFIX=F:/ffmpeg/ffmpeg/android/$CPU
export ADDI_CFLAGS="-marm"

./configure --target-os=android \
--prefix=$PREFIX --arch=arm \
--disable-doc \
--enable-shared \
--disable-static \
--disable-yasm \
--disable-symver \
--enable-gpl \
--disable-ffmpeg \
--disable-ffplay \
--disable-ffprobe \
--disable-ffserver \
--disable-doc \
--disable-symver \
--cross-prefix=$TOOLCHAIN/bin/arm-linux-androideabi- \
--enable-cross-compile \
--sysroot=$SYSROOT \
--extra-cflags="-Os -fpic $ADDI_CFLAGS" \
--extra-ldflags="$ADDI_LDFLAGS" \
$ADDITIONAL_CONFIGURE_FLAG
make clean
make
make install

# ./build_android.sh 执行如下
Makefile:163: /tests/Makefile: No such file or directory
make: *** 没有规则可制作目标“/tests/Makefile”。 停止。
Unknown option "--disable-ffserver".
See ./configure --help for available options.
Makefile:163: /tests/Makefile: No such file or directory
make: *** 没有规则可制作目标“/tests/Makefile”。 停止。
Makefile:163: /tests/Makefile: No such file or directory
make: *** 没有规则可制作目标“/tests/Makefile”。 停止。
Makefile:163: /tests/Makefile: No such file or directory
make: *** 没有规则可制作目标“/tests/Makefile”。 停止

**Comment by kaiwmtnk** [comment]
还是自己回答吧，这个是我没有先执行一次./configure,还有书中脚本的支持只能在小于等于android-ndk-r15c版本才能执行

**Comment by smartyuge** [comment]
你好，这个是ffmpeg 3.1.3的版本，随书源码有3.1.3的版本下载。
