### ISSUE TITLE
这本书可以说是一本诱导消费者的书.

### ISSUE THREAD

**Issue by hdyip** [hejunlin2013/AVBookCode#13]
第一, 书名叫 xxx 音视频开发. 但是,只讲解码,不讲推流,也不讲直播. 推流拉流部分一句话带过. 
第二,可以网上几块钱买个电子版看看.不然真的是浪费钱.

**Comment by hdyip** [comment]
第三,看完这本书我们能做什么? 能实时解码视频? 能做直播? 既然不能, 还有什么意义?

**Comment by hdyip** [comment]
真是越看越恼火. ffmpeg这块,书本给的例子还没有网上的多. 音频和视频单独写例子, 音视频同步重来不讲.既然没有贡献精神,就不要写这本书.都不知道写这本书的意义是什么?

**Comment by smartyuge** [comment]
推流和直播都有涉及，其中有一个专门介绍写一个推流器的案例。如果不能让你满意，是我的遗憾~
